name: Fake building

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: run something
      run: |
        echo hello world

    - name: run something
      run: |
        sleep 60
        echo .
        exit 1
