name: Fake building

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: run something
      run: |
        echo hello world

    - name: run something
      run: |
        sleep 5
        echo .
        exit 1
        
    - name: Step To run on failure
      if: ${{ failure() }}
      run: echo failure!

    - name: Step To run on success
      if: ${{ success() }}
      run: echo success!