name: Fake workflow

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:

    - name: Connecting the GitHub workflow to Husarnet VPN network
      uses: husarnet/husarnet-action@v2
      with:
        join-code: ${{ secrets.HUSARNET_JOINCODE }}

    - name: Set Christmas tree yellow
      run: curl http://pixel-led-chain:8080/color=yellow

    - name: Test failure
      if: ${{ failure() }}
      run: echo "test failure"

    - name: Test success
      if: ${{ success() }}
      run: echo "test success"

    - name: run something that fails
      run: |
        echo "building something..."
        sleep 5
        echo "testing somethings..."
        sleep 5
        echo "fail!"
        exit 1

    # - name: run something that does not fail
    #   run: |
    #     echo "building something..."
    #     sleep 5
    #     echo "testing somethings..."
    #     sleep 5
    #     echo "success!"
        
    - name: Step to run on failure
      if: ${{ failure() }}
      run: curl http://pixel-led-chain:8080/color=red

    - name: Step to run on success
      if: ${{ success() }}
      run: curl http://pixel-led-chain:8080/color=green