name: Status LED

on:
  workflow_run:
    workflows: ["Fake building"]
    types:
      - completed
      - requested

jobs:
  led-yellow:
    runs-on: ubuntu-20.04
    if: ${{ github.event.action == 'requested' }}
    
    steps:
    - name: Connecting the GitHub workflow to Husarnet VPN network
      uses: husarnet/husarnet-action@v2
      with:
        join-code: ${{ secrets.HUSARNET_JOINCODE }}

    - name: print context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

    - name: Set LED
      run: curl ${{ secrets.HUSARNET_HOSTNAME }}:8080/color=yellow

    - name: Stop Husarnet
      run: sudo systemctl stop husarnet

  on-success:
    runs-on: ubuntu-20.04
    if: ${{ github.event.action == 'completed' && github.event.workflow_run.conclusion == 'success' }}
    # if: ${{ github.event.action == 'completed' }}

    steps:
    - name: Connecting the GitHub workflow to Husarnet VPN network
      uses: husarnet/husarnet-action@v2
      with:
        join-code: ${{ secrets.HUSARNET_JOINCODE }}

    - name: Set LED
      run: curl ${{ secrets.HUSARNET_HOSTNAME }}:8080/color=green

    - name: Stop Husarnet
      run: sudo systemctl stop husarnet

  on-failure:
    runs-on: ubuntu-20.04
    if: ${{ github.event.action == 'completed' && github.event.workflow_run.conclusion == 'failure' }}
    
    steps:
    - name: Connecting the GitHub workflow to Husarnet VPN network
      uses: husarnet/husarnet-action@v2
      with:
        join-code: ${{ secrets.HUSARNET_JOINCODE }}

    - name: Set LED
      run: curl ${{ secrets.HUSARNET_HOSTNAME }}:8080/color=red

    - name: Stop Husarnet
      run: sudo systemctl stop husarnet